In [15]:
# NumPy Array Creation

import numpy as np

# Creating arrays 
# try adding the suffix _like after the functions below
array = np.array([1, 2, 3])
zeros = np.zeros((3, 3))
ones = np.ones((2, 2))
full = np.full((2, 3), 7)
empty = np.empty((2, 2))


# Displaying arrays
print("Array:", array)
print("Zeros:", zeros)
print("Ones:", ones)

# create the identity
eye = np.eye(3)
identity = np.identity(4)
print("Eye:", eye)
print("Identity:", identity)

Array: [1 2 3]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1.]
 [1. 1.]]
Eye: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Identity: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# linspace split the interval according to the step
# but arange just specify the step
arange = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)
logspace = np.logspace(start=10, stop=100, num=4, endpoint=True, base=2)

print("Arange:", arange)
print("Linspace:", linspace)
print("Logspace:", logspace)

Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Logspace: [1.02400000e+03 1.09951163e+12 1.18059162e+21 1.26765060e+30]


In [14]:
# so we can find that the logspace 
# is just the base ** linspace with same params
2 ** np.linspace(10, 100, 4, endpoint=True)

array([1.02400000e+03, 1.09951163e+12, 1.18059162e+21, 1.26765060e+30])