In [2]:
# NumPy Array Manipulation

import numpy as np

# Array creation
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", a)

# Reshaping
reshaped = a.reshape((3, 2))
print("Reshaped array:\n", reshaped)

# Transpose
transposed = a.transpose()
print("Transposed array:\n", transposed)

# Concatenation
b = np.array([[7, 8, 9]])
concatenated = np.concatenate((a, b), axis=0)
print("Concatenated array:\n", concatenated)

# Stacking(vtack, hstack, concatenate + axis-specified)
stacked = np.stack((a, a))
print("Stacked array:\n", stacked)

# Splitting
split = np.split(a, 3, axis=1)
print("Split array:\n", split)


Original array:
 [[1 2 3]
 [4 5 6]]
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]
Transposed array:
 [[1 4]
 [2 5]
 [3 6]]
Concatenated array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Stacked array:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Split array:
 [array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [3]:
# So ravel will return a reference if the ndarray is contiguous
# otherwise return a copy with new data !!!  

# Contiguous memory (C-order)
a = np.array([[1, 2, 3], [4, 5, 6]])
raveled_a = a.ravel()

print("Original array (contiguous):")
print(a)
print("Raveled array (contiguous):")
print(raveled_a)

# Modify the raveled array and observe the original array
raveled_a[0] = 10
print("\nModified raveled array:")
print(raveled_a)
print("Original array after modification:")
print(a)

# Non-contiguous memory (slice of array)
b = a[:, ::2]
raveled_b = b.ravel()

print("\nOriginal array (non-contiguous):")
print(b)
print("Raveled array (non-contiguous):")
print(raveled_b)

# Modify the raveled array and observe the original array
raveled_b[0] = 20
print("\nModified raveled array:")
print(raveled_b)
print("Original array after modification:")
print(b)


Original array (contiguous):
[[1 2 3]
 [4 5 6]]
Raveled array (contiguous):
[1 2 3 4 5 6]

Modified raveled array:
[10  2  3  4  5  6]
Original array after modification:
[[10  2  3]
 [ 4  5  6]]

Original array (non-contiguous):
[[10  3]
 [ 4  6]]
Raveled array (non-contiguous):
[10  3  4  6]

Modified raveled array:
[20  3  4  6]
Original array after modification:
[[10  3]
 [ 4  6]]
