In [1]:
# NumPy Indexing and Slicing

import numpy as np

# Array creation
a = np.array([1, 2, 3, 4, 5])

# Indexing
print("Element at index 2:", a[2])

# Slicing
print("Elements from index 1 to 4:", a[1:4])

# Fancy indexing
b = np.array([1, 2, 3, 4, 5, 6])
indices = [0, 2, 4]
print("Elements at indices 0, 2, 4:", b[indices])

# Boolean indexing
c = np.array([1, 2, 3, 4, 5, 6])
print("Elements greater than 3:", c[c > 3])


Element at index 2: 3
Elements from index 1 to 4: [2 3 4]
Elements at indices 0, 2, 4: [1 3 5]
Elements greater than 3: [4 5 6]


In [2]:
matrix = np.arange(25).reshape(5, 5)

# Find indices of even numbers
indices = np.where(matrix % 2 == 0)
print("Indices of even numbers:\n", indices)

# Use these indices to get the elements
even_numbers = matrix[indices]
print("Even numbers:\n", even_numbers)

matrix[matrix % 2 == 0]

Indices of even numbers:
 (array([0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 4, 4, 4]), array([0, 2, 4, 1, 3, 0, 2, 4, 1, 3, 0, 2, 4]))
Even numbers:
 [ 0  2  4  6  8 10 12 14 16 18 20 22 24]


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [3]:
array_3d = np.random.randint(0, 11, size=(3, 3, 3))

# Replace values greater than 5 with 10
new_array_3d = np.where(array_3d > 5, 10, array_3d)
print("Original array:\n", array_3d)
print("Modified array:\n", new_array_3d)

Original array:
 [[[10  7 10]
  [ 6  7  6]
  [ 4  2  4]]

 [[ 4  7  7]
  [10  3  9]
  [ 2  3  5]]

 [[ 5  2  8]
  [ 3  8  9]
  [ 2  9  2]]]
Modified array:
 [[[10 10 10]
  [10 10 10]
  [ 4  2  4]]

 [[ 4 10 10]
  [10  3 10]
  [ 2  3  5]]

 [[ 5  2 10]
  [ 3 10 10]
  [ 2 10  2]]]


In [4]:
import numpy as np
import numpy.ma as ma

a = np.array([1, 2, 3, 4, 5])
mask = [0, 1, 0, 1, 0]

# Create a masked array (it's interesting cuz it can replace the data with the placeholder '--')
masked_array = ma.masked_array(a, mask=mask)
print("Masked array:", masked_array)
print("Data without masked elements:", masked_array.compressed())

Masked array: [1 -- 3 -- 5]
Data without masked elements: [1 3 5]


In [8]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Extract elements greater than 5
extracted_elements = np.extract(a > 5, a)
print("Extracted elements:", extracted_elements)
# extraction will flatten the data extracted from the array
b = np.random.randint(1, 10, (50, 50))
np.extract(b >= 5, b)

Extracted elements: [ 6  7  8  9 10]


array([5, 5, 7, ..., 5, 5, 6], dtype=int32)