In [1]:
# NumPy Linear Algebra

import numpy as np

# Array creation
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Dot product
print("Dot product:\n", np.dot(a, b))

# Matrix multiplication
print("Matrix multiplication:\n", np.matmul(a, b))

# Determinant
print("Determinant:", np.linalg.det(a))

# Inverse
print("Inverse:\n", np.linalg.inv(a))

# Eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(a)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)



Dot product:
 [[19 22]
 [43 50]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Singular values: [5.4649857  0.36596619]
V:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [14]:
# A @ eigenvecs == eigenvals @ eigenvecs
# a @ eigvecs[:, 1], eigvals[1] * eigvecs[:, 1]
a @ eigvecs, eigvals * eigvecs 
# a @ eigvecs == eigvals * eigvecs 

(array([[ 0.30697009, -2.23472698],
        [-0.21062466, -4.88542751]]),
 array([[ 0.30697009, -2.23472698],
        [-0.21062466, -4.88542751]]))

In [17]:
"""
    U : mxm matrix
    S : sigma values
    V : nxn matrix
"""
# Singular Value Decomposition (SVD)
a2SVD = np.array([[1, 2], [2, 3], [3, 4]])
U, S, V = np.linalg.svd(a2SVD)
print("U:\n", U)
print("Singular values:", S)
print("V:\n", V)

U @ a2SVD @ V

U:
 [[-0.33809817  0.84795222  0.40824829]
 [-0.55064932  0.17354729 -0.81649658]
 [-0.76320047 -0.50085764  0.40824829]]
Singular values: [6.54675564 0.37415323]
V:
 [[-0.56959484 -0.82192562]
 [-0.82192562  0.56959484]]


array([[-4.34828457, -0.12871079],
       [ 4.67281494, -0.01042282],
       [ 1.45507084, -0.35116312]])