In [2]:
# All these operations is based on the manipulation of the data
import numpy as np

# Random seed
np.random.seed(0)

# Uniform distribution
print("Uniform distribution:\n", np.random.rand(3, 3))

# Standard normal distribution
print("Standard normal distribution:\n", np.random.randn(3, 3))

# Random integers
print("Random integers:\n", np.random.randint(0, 10, (3, 3)))

# Random choice
print("Random choice:", np.random.choice([1, 2, 3, 4, 5], size=3))

# Set random seed
np.random.seed(42)
print("Random numbers with seed 42:\n", np.random.rand(3, 3))


Uniform distribution:
 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
Standard normal distribution:
 [[ 1.26611853 -0.50587654  2.54520078]
 [ 1.08081191  0.48431215  0.57914048]
 [-0.18158257  1.41020463 -0.37447169]]
Random integers:
 [[0 1 9]
 [9 0 4]
 [7 3 2]]
Random choice: [5 3 1]
Random numbers with seed 42:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]
