In [1]:
# NumPy Broadcasting
import numpy as np

# Array creation
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

# Broadcasting addition
print("Broadcasting addition:\n", a + b)

# Broadcasting multiplication
print("Broadcasting multiplication:\n", a * b)

# Broadcasting to a new shape
c = np.broadcast_to(a, (3, 3))
print("Broadcasted array:\n", c)

# Broadcasting arrays
d, e = np.broadcast_arrays(a, b)
print("Broadcasted arrays:\n", d, e)


Broadcasting addition:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]
Broadcasting multiplication:
 [[1 2 3]
 [2 4 6]
 [3 6 9]]
Broadcasted array:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
Broadcasted arrays:
 [[1 2 3]
 [1 2 3]
 [1 2 3]] [[1 1 1]
 [2 2 2]
 [3 3 3]]


In [ ]:
x