In [2]:
# NumPy File I/O

import numpy as np

# Array creation
a = np.array([[1, 2, 3], [4, 5, 6]])

# Save array to a text file
np.savetxt("array.txt", a)
print("Array saved to array.txt")

# Load array from a text file
loaded_array = np.loadtxt("array.txt")
print("Loaded array from array.txt:\n", loaded_array)


Array saved to array.txt
Loaded array from array.txt:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
# the npy will just store one array
# Save array to a binary file
np.save("array.npy", a)
print("Array saved to array.npy")

# Load array from a binary file
loaded_binary_array = np.load("array.npy")
print("Loaded array from array.npy:\n", loaded_binary_array)

Array saved to array.npy
Loaded array from array.npy:
 [[1 2 3]
 [4 5 6]]


In [9]:
# Save multiple arrays to a compressed file
np.savez("arrays.npz", *[a**i for i in range(5)])
print("Arrays saved to arrays.npz")

# Load multiple arrays from a compressed file
loaded_arrays = np.load("arrays.npz")
print("Loaded arrays from arrays.npz:")
print(loaded_arrays)
for i,j in loaded_arrays.items():
    print(i, j)

Arrays saved to arrays.npz
Loaded arrays from arrays.npz:
NpzFile 'arrays.npz' with keys: arr_0, arr_1, arr_2, arr_3, arr_4
arr_0 [[1 1 1]
 [1 1 1]]
arr_1 [[1 2 3]
 [4 5 6]]
arr_2 [[ 1  4  9]
 [16 25 36]]
arr_3 [[  1   8  27]
 [ 64 125 216]]
arr_4 [[   1   16   81]
 [ 256  625 1296]]
