## Manipulation

In [2]:
import numpy as np

# dstack like padding the same pos element together
a = np.random.randn(3, 3)
b = np.random.randn(3, 3)

c = np.dstack((a, b))
c.shape

(3, 3, 2)

In [3]:
# if the ndim > 2 then how the vstack and hstack work?
a = np.random.randn(1, 32, 64, 64)
b = np.random.randn(1, 32, 64, 64)

[f"{func.__name__} : {func((a,b)).shape}"  for func in (np.vstack, np.hstack, np.dstack)]

['vstack : (2, 32, 64, 64)',
 'hstack : (1, 64, 64, 64)',
 'dstack : (1, 32, 128, 64)']

In [4]:
# we found that the (v, h, d) actually work in three different dimensions
# while we can use the concatenate to work on the last axis
np.concatenate((a, b), axis=3).shape

(1, 32, 64, 128)

In [5]:
# concat is registered as 'concatenate'
y = None
np.concat((a, b), axis=-1, out=y)
np.array(list((a, b))).shape

(2, 1, 32, 64, 64)

In [6]:
# split
[i.shape for i in np.vsplit(np.random.randn(2, 1, 1, 1), 2)]

[(1, 1, 1, 1), (1, 1, 1, 1)]

In [7]:
[i.shape for i in np.hsplit(a, 2)]

[(1, 16, 64, 64), (1, 16, 64, 64)]

In [8]:
[i.shape for i in np.split(a, 4, axis=3)]

[(1, 32, 64, 16), (1, 32, 64, 16), (1, 32, 64, 16), (1, 32, 64, 16)]

In [9]:
# this received list means the span of each sublist
[i.shape for i in np.split(a, [16, 32], axis=2)]

[(1, 32, 16, 64), (1, 32, 16, 64), (1, 32, 32, 64)]

In [10]:
[i.shape for i in np.dsplit(a, 4)]

[(1, 32, 16, 64), (1, 32, 16, 64), (1, 32, 16, 64), (1, 32, 16, 64)]

In [11]:
a = np.random.randint(1, 10, (10,))
profit_prob = np.diff(a) / a[:-1]
a, np.diff(a), profit_prob

(array([7, 2, 7, 7, 5, 6, 1, 5, 7, 1], dtype=int32),
 array([-5,  5,  0, -2,  1, -5,  4,  2, -6], dtype=int32),
 array([-0.71428571,  2.5       ,  0.        , -0.28571429,  0.2       ,
        -0.83333333,  4.        ,  0.4       , -0.85714286]))

In [12]:
d = np.random.randn(3, 3)
d > 0.5, d[d > 0.5]
# d.compress(d > 0.5), np.where(d > 0.5)

(array([[ True, False, False],
        [ True,  True, False],
        [False, False,  True]]),
 array([0.67704199, 1.95520266, 0.72595789, 1.69943277]))

## Calculation

In [16]:
# broadcast
import numpy as np

a = np.random.randint(1, 5, (3, 3))
b = np.random.randint(1, 3, (1, 3))

a, b, a + b

(array([[4, 4, 3],
        [1, 3, 3],
        [1, 1, 2]], dtype=int32),
 array([[2, 1, 2]], dtype=int32),
 array([[6, 5, 5],
        [3, 4, 5],
        [3, 2, 4]], dtype=int32))